### ISSUE TITLE
cannot build the project

### ISSUE THREAD

**Issue by ferasdarkazanly** [RemiBou/Toss.Blazor#8]
Hi

i'm not able to build the project using Visual Studio 2019, the error message is :

Severity	Code	Description	Project	File	Line	Suppression State
Error	MSB4036	The "RazorGenerate" task was not found. Check the following: 1.) The name of the task in the project file is the same as the name of the task class. 2.) The task class is "public" and implements the Microsoft.Build.Framework.ITask interface. 3.) The task is correctly declared with <UsingTask> in the project file, or in the *.tasks files located in the "C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\MSBuild\Current\Bin" directory.	Toss.Client	C:\Program Files\dotnet\sdk\3.0.100-preview3-010431\Sdks\Microsoft.NET.Sdk.Razor\build\netstandard2.0\Microsoft.NET.Sdk.Razor.Component.targets	93	

i installed the Razor Generate extension but the problem is still there and i cannot build the project.

**Comment by RemiBou** [comment]
DO you have Blazor Language Service installed ? what is your version of the sdk ?

**Comment by Tirumalesh8686** [comment]
**When im building the Toss.Client...I got the following warnings...**

NETSDK1080	A PackageReference to Microsoft.AspNetCore.App is not necessary when targeting .NET Core 3.0 or higher. If Microsoft.NET.Sdk.Web is used, the shared framework will be referenced automatically. Otherwise, the PackageReference should be replaced with a FrameworkReference. Toss.Tests.E2E
C:\Program Files\dotnet\sdk\3.0.100-preview8-013656\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.DefaultItems.targets	154

NETSDK1080	A PackageReference to Microsoft.AspNetCore.App is not necessary when targeting .NET Core 3.0 or higher. If Microsoft.NET.Sdk.Web is used, the shared framework will be referenced automatically. Otherwise, the PackageReference should be replaced with a FrameworkReference. Toss.Tests
C:\Program Files\dotnet\sdk\3.0.100-preview8-013656\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.DefaultItems.targets	154

**When i tried to build the Toss.server i got the below error saying:**
Severity	Code	Description	Project	File	Line	Suppression State
Error:	Could not find file 'D:\User\Toss.Blazor-master\Toss.Client\bin\x64\Release\netstandard2.0\Toss.Client.dll'.	Toss.Server	C:\Program Files\dotnet\sdk\3.0.100-preview8 013656\Sdks\Microsoft.NET.Sdk.Razor\build\netstandard2.0\Microsoft.NET.Sdk.Razor.MvcApplicationPartsDiscovery.targets	54

there were many other errors too...but this the error which is not getting resolved......

**Comment by RemiBou** [comment]
You need 3.0.100-preview6-012264 for building master, the "conversation" branch is using "3.0.100-preview6-012264" i'll update it to preview8 and 9 soon.

The 2 warning about the App package are here because of E2E tests, I need this package ref because those are not web project if you know an other way I would be happy to correct it.
